name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - Release
trigger:
  branches:
    include:
      - Release

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_COAST_0BF333F0F)
    command: 'npm run build-test'
  ${{ if eq(variables['Build.SourceBranchName'], 'release-prod') }}:
    token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_PROD)
    command: 'npm run build-prod'


jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: azure-static-web-apps-polite-coast-0bf333f0f-variable-group
  steps: 
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_build_command: $(command)
      azure_static_web_apps_api_token: $(token)
###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "FrontEnd/cred-system-front-end-app/" # App source code path
      output_location: "dist"
###### End of Repository/Build Configurations ######

