const IMAGES = {
    logoComisionado : new URL('./logoGobierno.png', import.meta.url).href,
    logoDeptBlack : new URL('./OCSlogoBlack.png', import.meta.url).href,
    logoDeptWhite : new URL('./OCSlogoWhite.png', import.meta.url).href,
    iconFormCheckmark : new URL('./icFormCheckmark.png', import.meta.url).href,
    iconFormWarning : new URL('./icFormExclamationMark.png', import.meta.url).href,
    iconFormActive : new URL('./icFormBlueDot.png', import.meta.url).href,
    iconFormInactive : new URL('./icFormGrayDot.png', import.meta.url).href,
    iconCongratulationCheckmark : new URL('./icCongratulationCheckmark.png', import.meta.url).href,
    iconMessageBubble : new URL('./icMessageBubble.png', import.meta.url).href,
    iconDownload : new URL('./icDownload.png', import.meta.url).href,
    signupScreenOne:new URL('./signup_screen_1.svg', import.meta.url).href,
    iconSearch : new URL('./icSearch.png', import.meta.url).href,
    iconHelp : new URL('./icHelpQuestionMark.png', import.meta.url).href,
    imgNotFound : new URL('./imgNotFound.svg', import.meta.url).href,
    signupComplete: new URL('./signupComplete.svg', import.meta.url).href,
    imgLogin : new URL('./imgLogin.svg', import.meta.url).href,
    tnCertificatePreview : new URL('./tn_certificate_preview.png', import.meta.url).href,
    inviteForm : new URL('./invite_form.svg', import.meta.url).href,
    inviteSuccess : new URL('./invite_success.svg', import.meta.url).href,
    delegatesWelcome: new URL('./deleWelcome.svg', import.meta.url).href,
    providerWelcome: new URL('./providerWelcome.svg', import.meta.url).href,
    drXray: new URL('./drXray.svg', import.meta.url).href,
    drConsult:new URL('./drConsult.svg', import.meta.url).href,
    cardMediaThree:new URL('./card3Media.svg', import.meta.url).href,
    cardMediaOne:new URL('./card1Media.svg', import.meta.url).href,
    cardMediaTwo:new URL('./card2Media.svg', import.meta.url).href,
    cardMediaFour:new URL('./card4Media.svg', import.meta.url).href,
    iconClose:new URL('./icClose.svg', import.meta.url).href,
    landingImage1:new URL('./landingImage1.png', import.meta.url).href,
    landingImage2:new URL('./landingImage2.png', import.meta.url).href,
    userInfoSent:new URL('./userInfoSent.svg', import.meta.url).href,
    insuranceWelcome: new URL('./insuranceWelcome.svg', import.meta.url).href,
    bannerLandingPage: new URL('./banner.png', import.meta.url).href,
    mobileLandingPage: new URL('./mobileLandingPage.svg', import.meta.url).href,
    documentsImage: new URL('./documentsImage.png', import.meta.url).href,
    shieldLandingPage: new URL('./shieldIcon.svg', import.meta.url).href,
    circleArrowsIcon: new URL('./circleArrows.svg', import.meta.url).href,
    medicalSuit: new URL('./medicalSuit.svg', import.meta.url).href,
    healthProvider: new URL('./healthProvider.svg', import.meta.url).href,
    maleProvider: new URL('./maleProvider.svg', import.meta.url).href,
    femaleProvider: new URL('./femaleProvider.svg', import.meta.url).href,
    circleDiagonalLines: new URL('./circleDiagonalLines.svg', import.meta.url).href,
}

export default IMAGES